import type { NextPage } from 'next';
import Head from 'next/head';
import { useCallback, useEffect, useState } from 'react';
import Navbar from '../components/navbar';

const Home: NextPage = () => {
  const [mounted, setMounted] = useState(false);
  useEffect(() => {
    setMounted(true);
  }, []);

  if (!mounted) return null;
  else {
    const userTheme = localStorage.getItem('theme');
    const systemTheme = window.matchMedia(
      '(prefers-color-scheme: dark)'
    ).matches;

    if (userTheme === 'dark' || (!userTheme && systemTheme)) {
      document.documentElement.classList.add('dark');
      document.body.classList.add('body-dark');
    } else {
      document.documentElement.classList.remove('dark');
      document.body.classList.remove('body-dark');
    }

    const handleTheme = () => {
      if (document.documentElement.classList.contains('dark')) {
        document.documentElement.classList.remove('dark');
        document.body.classList.remove('body-dark');
        localStorage.setItem('theme', 'light');
        return;
      }
      document.documentElement.classList.add('dark');
      document.body.classList.add('body-dark');
      localStorage.setItem('theme', 'dark');
    };

    return (
      <div>
        <Head>
          <title>Alphalete</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <Navbar />
        <button onClick={handleTheme}>Change Theme</button>
      </div>
    );
  }
};

export default Home;
